#!/bin/bash 

###########################
#  Author :  Muhammad Usama
#  Object :  Understanding Arithmetic operators
#  Version : v1.0
#  Date : 31-07-2024
###########################

# Addition of 2 or more numbers
num1=35
num2=12

echo "num1 + num2 = " $((num1+num2))

# Subtraction of 2 or more numbers
num1=23
num2=17

echo "num1 - num2 = " $((num1-num2))

# Multiplication of 2 or more numbers
num1=9
num2=7

echo "num1 * num2 = " $((num1*num2))

# Division of 2 numbers or more numbers
num1=27
num2=3

echo "num1 / num2 = " $((num1/num2))

# Modulus of 2 or more numbers
num1=27
num2=3

echo "num1 % num2 = " $((num1%num2))

# Power of the number
num=2

echo "$num to the power of 3 = $( echo 2^3 | bc )"

echo " keep Learning!"
